"""
Problem - 02
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
array = []
a = 0
show = 0
i = 1
sum1 = 0
while show < 4000000:
    show = a + i
    a = i
    i = show
    array.append(show)
for num in array:
    if num % 2 == 0:
        sum1 += num
#print(array)
print(sum1)

